export enum CONNECTION {
  TEST_CONN_MAIN = "PG_TEST_CONN_MAIN",
  TRADE_DATA_MAIN = "PG_TRADE_DATA_MAIN",
  TRADE_ORDER_MAIN = "PG_TRADE_ORDER_MAIN",
  USER_SERVICE_MAIN = "PG_USER_SERVICE_MAIN",
  RELAY_SERVICE_MAIN = "PG_RELAY_SERVICE_MAIN",
  ACCESS_GATEWAY_MAIN = "PG_ACCESS_GATEWAY_MAIN",
  ACCESS_SERVICE_MAIN = "PG_ACCESS_SERVICE_MAIN",
  DASHBOARD_GATEWAY_MAIN = "PG_DASHBOARD_GATEWAY_MAIN",
  AUTHORIZATION_SERVICE_MAIN = "PG_AUTHORIZATION_SERVICE_MAIN",
  AUTHENTICATION_SERVICE_MAIN = "PG_AUTHENTICATION_SERVICE_MAIN",
}
