export enum PORTAL {
  AUTH = "AUTH",
  ADMIN = "ADMIN",
  TRADING = "TRADING",
  DASHBOARD = "DASHBOARD",
  WHITEBOARD = "WHITEBOARD",
}

export enum AUTH {
  TRADING = "TRADING",
  DASHBOARD = "DASHBOARD",
  WHITEBOARD = "WHITEBOARD",
}

export enum USER {
  ADMIN = "ADMIN",
  TRADING = "TRADING",
  DASHBOARD = "DASHBOARD",
  WHITEBOARD = "WHITEBOARD",
}
