export enum CONNECTION {
  AUTH_GATEWAY_MAIN = "AUTH_GATEWAY_MAIN",
  AUTH_SERVICE_MAIN = "AUTH_SERVICE_MAIN",
  TRADING_DATA_MAIN = "TRADING_DATA_MAIN",
  USER_SERVICE_MAIN = "USER_SERVICE_MAIN",
  RELAY_SERVICE_MAIN = "RELAY_SERVICE_MAIN",
}
