export enum CONNECTION {
  TEST_CONN_MAIN = "TEST_CONN_MAIN",
  TRADE_DATA_MAIN = "TRADE_DATA_MAIN",
  TRADE_ORDER_MAIN = "TRADE_ORDER_MAIN",
  USER_SERVICE_MAIN = "USER_SERVICE_MAIN",
  RELAY_SERVICE_MAIN = "RELAY_SERVICE_MAIN",
  ACCESS_GATEWAY_MAIN = "ACCESS_GATEWAY_MAIN",
  ACCESS_SERVICE_MAIN = "ACCESS_SERVICE_MAIN",
  DASHBOARD_GATEWAY_MAIN = "DASHBOARD_GATEWAY_MAIN",
  AUTHORIZATION_SERVICE_MAIN = "AUTHORIZATION_SERVICE_MAIN",
  AUTHENTICATION_SERVICE_MAIN = "AUTHENTICATION_SERVICE_MAIN",
}
