export enum CONNECTION {
  TEST_CONN_MAIN = "MG_TEST_CONN_MAIN",
  TRADE_DATA_MAIN = "MG_TRADE_DATA_MAIN",
  TRADE_ORDER_MAIN = "MG_TRADE_ORDER_MAIN",
  USER_SERVICE_MAIN = "MG_USER_SERVICE_MAIN",
  RELAY_SERVICE_MAIN = "MG_RELAY_SERVICE_MAIN",
  ACCESS_GATEWAY_MAIN = "MG_ACCESS_GATEWAY_MAIN",
  ACCESS_SERVICE_MAIN = "MG_ACCESS_SERVICE_MAIN",
  DASHBOARD_GATEWAY_MAIN = "MG_DASHBOARD_GATEWAY_MAIN",
  AUTHORIZATION_SERVICE_MAIN = "MG_AUTHORIZATION_SERVICE_MAIN",
  AUTHENTICATION_SERVICE_MAIN = "MG_AUTHENTICATION_SERVICE_MAIN",
}
