export enum DATABASE_CONNECTION_NAME {
  USER_DB = "USER_DB",
  RELAY_DB = "RELAY_DB",
  AUTH_GATEWAY_DB = "AUTH_GATEWAY_DB",
  AUTH_SERVICE_DB = "AUTH_SERVICE_DB",
  TRADING_DATA_DB = "TRADING_DATA_DB",
}
